export const SHOOT_COOLDOWN = 250;
export const BULLET_SPEED = 3.5;
export const SHIP_ROT_SPEED = 0.055;
export const SHIP_THRUST = 0.18;
export const SHIP_DRAG = 0.985;
export const SHIP_SIZE = 14;
export const POINTS_BY_SIZE = { 1: 100, 2: 50, 3: 20 }
export const ASTEROID_RADIUS_SCALE = 18;
export const ASTEROID_SPEED = 3;